[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "tags"
  weight = 20

# [[main]]
#   name = "GitHub"
#   url = "https://github.com/mikesmithgh"
#   weight = 30
#   [main.params]
#     icon = "github"
#     showName = false
#     target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Blog Menu"
  pageRef = "posts"

[[footer]]
  name = "Blog Menu 2"
  pageRef = "posts"

