# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true
dateFormat = "Jan 2 2006"
description = "Mike Smith's Blog"
# mainSections = ["posts"]
# darkMode = "auto"
# darkToggle = false
# logo = "img/logo.jpg"
# robots = ""

[header]
  layout = "basic"
  # logo =
  # logoDark =
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = false

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 10

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = ""
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showWordCount = false
  showTableOfContents = false
  showTaxonomies = true
  showComments = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  groupByYear = true
  showTableOfContents = false
  paginationWidth = 1
  showTaxonomies = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

